# These are the sources from which librocksdb.a is built:
LIB_SOURCES =                                                   \
  db/auto_roll_logger.cc                                        \
  db/builder.cc                                                 \
  db/column_family.cc                                           \
  db/compacted_db_impl.cc                                       \
  db/compaction.cc                                              \
  db/compaction_iterator.cc                                     \
  db/compaction_job.cc                                          \
  db/compaction_picker.cc                                       \
  db/convenience.cc                                             \
  db/db_filesnapshot.cc                                         \
  db/dbformat.cc                                                \
  db/db_impl.cc                                                 \
  db/db_impl_debug.cc                                           \
  db/db_impl_readonly.cc                                        \
  db/db_impl_experimental.cc                                    \
  db/db_info_dumper.cc                                          \
  db/db_iter.cc                                                 \
  db/event_helpers.cc                                           \
  db/file_indexer.cc                                            \
  db/filename.cc                                                \
  db/flush_job.cc                                               \
  db/flush_scheduler.cc                                         \
  db/forward_iterator.cc                                        \
  db/internal_stats.cc                                          \
  db/log_reader.cc                                              \
  db/log_writer.cc                                              \
  db/managed_iterator.cc                                        \
  db/memtable_allocator.cc                                      \
  db/memtable.cc                                                \
  db/memtable_list.cc                                           \
  db/merge_helper.cc                                            \
  db/merge_operator.cc                                          \
  db/repair.cc                                                  \
  db/slice.cc                                                   \
  db/snapshot_impl.cc                                           \
  db/table_cache.cc                                             \
  db/table_properties_collector.cc                              \
  db/transaction_log_impl.cc                                    \
  db/version_builder.cc                                         \
  db/version_edit.cc                                            \
  db/version_set.cc                                             \
  db/wal_manager.cc                                             \
  db/write_batch.cc                                             \
  db/write_batch_base.cc                                        \
  db/write_controller.cc                                        \
  db/write_thread.cc                                            \
  memtable/skiplistrep.cc                                       \
  port/stack_trace.cc                                           \
  port/port_posix.cc                                            \
  table/adaptive_table_factory.cc                               \
  table/block_based_filter_block.cc                             \
  table/block_based_table_builder.cc                            \
  table/block_based_table_factory.cc                            \
  table/block_based_table_reader.cc                             \
  table/column_table_builder.cc                            	\
  table/column_table_factory.cc                            	\
  table/column_table_reader.cc                             	\
  table/block_builder.cc                                        \
  table/block.cc                                                \
  table/flush_block_policy.cc                                   \
  table/format.cc                                               \
  table/full_filter_block.cc                                    \
  table/get_context.cc                                          \
  table/iterator.cc                                             \
  table/merger.cc                                               \
  table/meta_blocks.cc                                          \
  table/sst_file_writer.cc                                      \
  table/table_properties.cc                                     \
  table/two_level_iterator.cc                                   \
  util/arena.cc                                                 \
  util/bloom.cc                                                 \
  util/build_version.cc                                         \
  util/cache.cc                                                 \
  util/coding.cc                                                \
  util/comparator.cc                                            \
  util/compaction_job_stats_impl.cc                             \
  util/concurrent_arena.cc                                      \
  util/crc32c.cc                                                \
  util/delete_scheduler.cc                                      \
  util/dynamic_bloom.cc                                         \
  util/env.cc                                                   \
  util/env_posix.cc                                             \
  util/io_posix.cc                                              \
  util/threadpool.cc                                            \
  util/sst_file_manager_impl.cc                                 \
  util/file_util.cc                                             \
  util/file_reader_writer.cc                                    \
  util/filter_policy.cc                                         \
  util/hash.cc                                                  \
  util/histogram.cc                                             \
  util/instrumented_mutex.cc                                    \
  util/iostats_context.cc                                       \
  util/event_logger.cc                                          \
  util/log_buffer.cc                                            \
  util/logging.cc                                               \
  util/murmurhash.cc                                            \
  util/mutable_cf_options.cc                                    \
  util/options.cc                                               \
  util/options_helper.cc                                        \
  util/options_parser.cc                                        \
  util/options_sanity_check.cc                                  \
  util/perf_context.cc                                          \
  util/perf_level.cc                                            \
  util/random.cc                                                \
  util/slice.cc                                                 \
  util/statistics.cc                                            \
  util/status.cc                                                \
  util/status_message.cc                                        \
  util/string_util.cc                                           \
  util/sync_point.cc                                            \
  util/thread_local.cc                                          \
  util/thread_status_impl.cc                                    \
  util/thread_status_updater.cc                                 \
  util/thread_status_updater_debug.cc                           \
  util/thread_status_util.cc                                    \
  util/thread_status_util_debug.cc                              \

TOOL_SOURCES = \

MOCK_SOURCES = \
  table/mock_table.cc \
  util/mock_env.cc \
  util/fault_injection_test_env.cc

BENCH_SOURCES = \
  tools/db_bench_tool.cc

TEST_BENCH_SOURCES =                                                    \
  third-party/gtest-1.7.0/fused-src/gtest/gtest-all.cc                  \
  db/auto_roll_logger_test.cc                                           \
  db/column_family_test.cc                                              \
  db/compaction_job_test.cc                                             \
  db/compaction_job_stats_test.cc                                       \
  db/compaction_picker_test.cc                                          \
  db/comparator_db_test.cc                                              \
  db/corruption_test.cc                                                 \
  tools/db_bench_tool.cc                                                \
  db/dbformat_test.cc                                                   \
  db/db_iter_test.cc                                                    \
  db/db_test.cc                                                         \
	db/db_block_cache_test.cc																							\
  db/db_io_failure_test.cc                                              \
  db/db_bloom_filter_test.cc                                            \
  db/db_compaction_filter_test.cc                                       \
  db/db_compaction_test.cc                                              \
  db/db_dynamic_level_test.cc                                           \
  db/db_inplace_update_test.cc                                          \
	db/db_iterator_test.cc																								\
  db/db_log_iter_test.cc                                                \
	db/db_sst_test.cc																											\
  db/db_tailing_iter_test.cc                                            \
  db/db_universal_compaction_test.cc                                    \
  db/db_wal_test.cc                                                     \
  db/db_table_properties_test.cc                                        \
  db/deletefile_test.cc                                                 \
  db/fault_injection_test.cc                                            \
  db/file_indexer_test.cc                                               \
  db/filename_test.cc                                                   \
  db/flush_job_test.cc                                                  \
  db/inlineskiplist_test.cc                                             \
  db/listener_test.cc                                                   \
  db/log_test.cc                                                        \
  db/manual_compaction_test.cc                                          \
  db/memtablerep_bench.cc                                               \
  db/merge_test.cc                                                      \
  db/options_file_test.cc                                               \
  db/perf_context_test.cc                                               \
  db/skiplist_test.cc                                                   \
  db/table_properties_collector_test.cc                                 \
  db/db_test_util.cc                                                    \
  db/version_builder_test.cc                                            \
  db/version_edit_test.cc                                               \
  db/version_set_test.cc                                                \
  db/wal_manager_test.cc                                                \
  db/write_batch_test.cc                                                \
  db/write_controller_test.cc                                           \
  db/write_callback_test.cc                                             \
  table/block_based_filter_block_test.cc                                \
  table/block_test.cc                                                   \
  table/full_filter_block_test.cc                                       \
  table/merger_test.cc                                                  \
  table/table_reader_bench.cc                                           \
  table/table_test.cc                                                   \
  tools/db_bench_tool_test.cc                                           \
  tools/db_sanity_test.cc                                               \
  util/arena_test.cc                                                    \
  util/autovector_test.cc                                               \
  util/bloom_test.cc                                                    \
  util/cache_bench.cc                                                   \
  util/cache_test.cc                                                    \
  util/coding_test.cc                                                   \
  util/crc32c_test.cc                                                   \
  util/dynamic_bloom_test.cc                                            \
  util/env_test.cc                                                      \
  util/filelock_test.cc                                                 \
  util/histogram_test.cc                                                \
  utilities/env_registry_test.cc                                        \
	util/iostats_context_test.cc																					\
  util/log_write_bench.cc                                               \
  util/mock_env_test.cc                                                 \
  util/options_test.cc                                                  \
  util/event_logger_test.cc                                             \
  util/rate_limiter_test.cc                                             \
  util/slice_transform_test.cc                                          \
  util/testharness.cc                                                   \
  util/testutil.cc                                                      \
  util/thread_list_test.cc                                              \
  util/thread_local_test.cc
